---

- name: 'Update apt'
  apt: update_cache=yes cache_valid_time=86400

- name: 'Install base dependencies'
  apt: name='{{ item }}' state=present
  with_items:
     - git
     - python-pip
     - python-virtualenv
     - python2.7
     - python2.7-dev
     - supervisor
     - vim

- name: 'Start supervisor service'
  service: name=supervisor state=started

- name: 'ensure github.com is a known host'
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: '^github\\.com'

- name: 'Clone/update web repo'
  git: repo='{{ web_repo }}' dest='{{ web_dir }}' version='{{ deploy_sha }}'
  when: not development
