---

- name: 'Update apt'
  apt: update_cache=yes cache_valid_time=86400

- name: 'Install common dependencies'
  apt: name='{{ item }}' state=present
  with_items:
     - build-essential
     - git
     - libxml2-dev
     - libxslt-dev
     - python-pip
     - python-virtualenv
     - python2.7
     - python2.7-dev
     - supervisor
     - vim
     - zlib1g-dev
