---

- name: 'Ensure docker group is present'
  group: name=docker state=present

- name: 'Ensure jenkins user belongs to the docker group'
  user: name=jenkins groups=docker append=yes

- name: 'Install infer docker image'
  docker: name=infer image=doctorq/infer:v1.1 state=present

- name: 'Install nokogiri'
  gem: name=nokogiri state=present
  become: yes
  become_user: jenkins
