---

- hosts: staging
  user: root
  sudo: yes
  sudo_user: root
  roles:
     - angstwad.docker_ubuntu
     - common
     - geerlingguy.java
     - geerlingguy.ruby
     - infer
     - jenkins
  vars_files:
    - vars/common.yml
    - vars/production.yml
