---

- hosts: staging
  user: root
  sudo: yes
  sudo_user: root
  roles:
     - common
     - web
     - geerlingguy.java
     - jenkins
  vars_files:
    - vars/common.yml
    - vars/production.yml
